version: "3.8"

services:

  build:
    image: node:20.11.0-alpine3.19
    user: "nodeuser"
    build: .
    ports:
      - 3000:3000
      - 9229:9229 # debuger
    environment:
      - PORT=${PORT}
      - HOST=${HOST}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M